# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ch_properties.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ch_properties(object):
    def setupUi(self, ch_properties):
        ch_properties.setObjectName("ch_properties")
        ch_properties.resize(377, 205)
        self.centralwidget = QtWidgets.QWidget(ch_properties)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 351, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_6)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        ch_properties.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ch_properties)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 26))
        self.menubar.setObjectName("menubar")
        ch_properties.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ch_properties)
        self.statusbar.setObjectName("statusbar")
        ch_properties.setStatusBar(self.statusbar)

        self.retranslateUi(ch_properties)
        QtCore.QMetaObject.connectSlotsByName(ch_properties)

    def retranslateUi(self, ch_properties):
        _translate = QtCore.QCoreApplication.translate
        ch_properties.setWindowTitle(_translate("ch_properties", "MainWindow"))
        self.label.setText(_translate("ch_properties", "signal color"))
        self.pushButton.setText(_translate("ch_properties", "choose color"))
        self.label_2.setText(_translate("ch_properties", "signal speed"))
        self.pushButton_2.setText(_translate("ch_properties", "slow down"))
        self.pushButton_5.setText(_translate("ch_properties", "reset"))
        self.pushButton_3.setText(_translate("ch_properties", "speed up"))
        self.label_5.setText(_translate("ch_properties", "rename"))
        self.label_4.setText(_translate("ch_properties", "add signal wave"))
        self.pushButton_4.setText(_translate("ch_properties", "open file"))
        self.label_3.setText(_translate("ch_properties", "signal display"))
        self.pushButton_6.setText(_translate("ch_properties", "choose signals"))
